import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docs: [
    {
      type: 'doc',
      label: '💡intro',
      id: 'index',
    },
    {
      type: 'category',
      label: '⚙️AWS',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'AWS',
        }
      ]
    },
    {
      type: 'category',
      label: '🏃work out',
        collapsed: true,
        items: [
            {
            type: 'autogenerated',
            dirName: 'exercise',
            }
            ]
    },
    {
      type: 'category',
      label: '🤖Machine Learning',
        collapsed: true,
        items: [
            {
            type: 'autogenerated',
            dirName: 'papers',
            }
            ]
    }
  ],
};

export default sidebars;
