on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18 # Use Node.js 18 here

      - name: Install dependencies
        working-directory: ./kirbee-website
        run: npm install

      - name: Build site
        env:
          REACT_APP_ALGOLIA_SEARCH_API_KEY: ${{ secrets.REACT_APP_ALGOLIA_SEARCH_API_KEY }}
          REACT_APP_ALGOLIA_APP_ID: ${{ secrets.REACT_APP_ALGOLIA_APP_ID }}
          REACT_APP_ALGOLIA_INDEX_NAME: ${{ secrets.REACT_APP_ALGOLIA_INDEX_NAME }}
        working-directory: ./kirbee-website
        run: npm run build
